# 服务器端口
server:
  port: 8080

spring:
  # 应用名称, 默认就是项目名称
  application:
    name: rg_task
  # 整合 mybatis
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/database1
      username: root
      password: 12345

  # 修改banner (输出log)
  main:
    banner-mode: off

mybatis-plus:
  configuration:
    # 映射实体或属性时, 去掉表名和字段的下划线, 采用驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

# 日志
logging:
  level:
    root: info